/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonProperty: typeof import('./components/PropertySetting/CommonProperty.vue')['default']
    Connect: typeof import('./components/registerNode/Connect.vue')['default']
    Control: typeof import('./components/LFComponents/Control.vue')['default']
    DataDialog: typeof import('./components/LFComponents/DataDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EventManageMent: typeof import('./components/statemachine/EventManageMent.vue')['default']
    LF: typeof import('./components/LF.vue')['default']
    NodePanel: typeof import('./components/LFComponents/NodePanel.vue')['default']
    PropertyDialog: typeof import('./components/PropertySetting/PropertyDialog.vue')['default']
    RightCollapse: typeof import('./components/collapse/RightCollapse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateManagement: typeof import('./components/statemachine/StateManagement.vue')['default']
  }
}
